
PLDM_MONITOR_GEN_DIR = $(SOURCE_DIR)/pkt_gen/pldm_gen/pldm_monitor_gen
INCLUDES += -I $(PLDM_MONITOR_GEN_DIR)

PLDM_MONITOR_GEN_C_SRCS = $(wildcard $(PLDM_MONITOR_GEN_DIR)/*.c)

C_SRCS += $(PLDM_MONITOR_GEN_C_SRCS)
